<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Ex03.GarageLogic</RootNamespace>
    <AssemblyName>Ex03.GarageLogic</AssemblyName>
  </PropertyGroup>

</Project>
